version: '3'
services:
  # myapplication:
  #   image: mongodb/mongodb-community-server:6.0-ubi8
  #   environment:
  #     - CONN_STR=mongodb://dalzemag:pwd123@mongodb
  #   command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
  #   depends_on:
  #     - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dalzemag
      - MONGO_INITDB_ROOT_PASSWORD=pwd123
    volumes:
      - type: bind
        source: ./mongodb/data
        target: /data/db
    ports:
      - 27017:27017